package net.jonasmf.auctionengine.repository.rds

import net.jonasmf.auctionengine.constant.Region
import java.time.LocalDate

data class CraftingMarketSearchRequest(
    val region: Region,
    val selectedConnectedRealmId: Int,
    val selectedDate: LocalDate,
    val selectedHour: Int,
    val commodityConnectedRealmId: Int,
    val commodityDate: LocalDate,
    val commodityHour: Int,
    val previousDate: LocalDate,
    val commodityPreviousDate: LocalDate,
    val localeColumnSuffix: String,
    val page: Int,
    val pageSize: Int,
    val sortBy: String,
    val sortDirection: String,
    val query: String?,
    val professionIds: List<Int>,
    val expansionIds: List<Int>,
    val qualityIds: List<Int>,
    val minProfit: Long?,
    val maxProfit: Long?,
    val minRoiPercent: Double?,
    val maxRoiPercent: Double?,
    val minSaleRatePercent: Double?,
    val maxSaleRatePercent: Double?,
    val minSoldPerDay: Double?,
    val maxSoldPerDay: Double?,
    val minReagentCost: Long?,
    val maxReagentCost: Long?,
    val minOutputPrice: Long?,
    val maxOutputPrice: Long?,
    val minOutputPriceChangePercent: Double?,
    val maxOutputPriceChangePercent: Double?,
    val requireCompleteReagentPricing: Boolean,
)

data class CraftingMarketSearchResult(
    val rows: List<CraftingMarketSqlRow>,
    val totalItems: Long,
)

data class CraftingMarketSqlRow(
    val recipeId: Int,
    val recipeRank: Int?,
    val craftedItemId: Int,
    val bonusKey: String,
    val modifierKey: String,
    val petSpeciesId: Int,
    val craftedQuantity: Int,
    val listingQuantity: Long?,
    val outputUnitPrice: Long?,
    val outputP25Price: Long?,
    val outputP75Price: Long?,
    val reagentCost: Long?,
    val profitCopper: Long?,
    val roiPercent: Double?,
    val outputPriceChangePercent: Double?,
    val profitChangePercent: Double?,
    val reagentsFullyPriced: Boolean,
    val recipeName: String?,
    val recipeMediaUrl: String?,
    val itemName: String,
    val itemMediaUrl: String?,
    val qualityId: Int?,
    val qualityType: String?,
    val qualityName: String?,
    val itemClassId: Int?,
    val itemClassName: String?,
    val itemSubclassId: Int?,
    val itemSubclassName: String?,
    val professionId: Int?,
    val professionName: String?,
    val expansionId: Int?,
    val skillTierName: String?,
    val professionCategoryName: String?,
    val saleRate: Double?,
    val soldPerDay: Double?,
)
