version: '3.1'
name: wow-auction-house

services:
  mariadb:
    image: mariadb:10.11
    ports:
      - "59000:3306"
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: root
    volumes:
      - "./docker/initdb:/docker-entrypoint-initdb.d:ro"

  floci:
    image: "hectorvent/floci:latest"
    ports:
      - "4566:4566"
    volumes:
      - "floci-data:/app/data"
    environment:
      FLOCI_STORAGE_MODE: persistent
      FLOCI_STORAGE_PERSISTENT_PATH: /app/data

volumes:
  floci-data:
