spring:
    test:
        constructor:
            autowire:
                mode: all
    cloud:
        aws:
            region:
                static: eu-west-1
            credentials:
                access-key: dummy-access-key
                secret-key: dummy-secret-key
            dynamodb:
                endpoint: ""
blizzard:
    client-id: dummy-client-id
    client-secret: dummy-client-secret
    region: Europe
    token-url: http://localhost/mock-blizzard/token
    base-url: http://localhost/mock-blizzard/api/
logging:
    level:
        org.springframework.context.support.PostProcessorRegistrationDelegate: ERROR
        org.springframework.context.support.PostProcessorRegistrationDelegate$BeanPostProcessorChecker: ERROR
        org.springframework.beans.factory.support.PostProcessorRegistrationDelegate$BeanPostProcessorChecker: ERROR
