spring:
    test:
        constructor:
            autowire:
                mode: all
    cloud:
        aws:
            region:
                static: eu-west-1
            credentials:
                access-key: dummy-access-key
                secret-key: dummy-secret-key
            dynamodb:
                endpoint: ""
            s3:
                endpoint: ""
                bootstrap-enabled: false
app:
    scheduling:
        enabled: false
blizzard:
    client-id: dummy-client-id
    client-secret: dummy-client-secret
    regions: ${WAE_BLIZZARD_REGIONS:${WAE_BLIZZARD_REGION:Europe}}
    token-url: http://localhost/mock-blizzard/token
    base-url: http://localhost/mock-blizzard/api/
wae:
    s3:
        buckets:
            northamerica:
                name: wah-data-us
                bucket-region: us-west-1
            europe:
                name: wah-data-eu
                bucket-region: eu-west-1
            korea:
                name: wah-data-as
                bucket-region: ap-northeast-2
            taiwan:
                name: wah-data-as
                bucket-region: ap-northeast-2
logging:
    level:
        org.springframework.context.support.PostProcessorRegistrationDelegate: ERROR
        org.springframework.context.support.PostProcessorRegistrationDelegate$BeanPostProcessorChecker: ERROR
        org.springframework.beans.factory.support.PostProcessorRegistrationDelegate$BeanPostProcessorChecker: ERROR

