CREATE OR REPLACE VIEW v_auction_market_item_details AS
SELECT
    i.id AS item_id,
    i.media_url AS item_media_url,
    i_l.de_de AS item_name_de_de,
    i_l.en_gb AS item_name_en_gb,
    i_l.en_us AS item_name_en_us,
    i_l.es_es AS item_name_es_es,
    i_l.es_mx AS item_name_es_mx,
    i_l.fr_fr AS item_name_fr_fr,
    i_l.it_it AS item_name_it_it,
    i_l.ko_kr AS item_name_ko_kr,
    i_l.pt_br AS item_name_pt_br,
    i_l.pt_pt AS item_name_pt_pt,
    i_l.ru_ru AS item_name_ru_ru,
    i_l.zh_cn AS item_name_zh_cn,
    i_l.zh_tw AS item_name_zh_tw,
    iq.internal_id AS quality_id,
    iq.type AS quality_type,
    iq_l.de_de AS quality_name_de_de,
    iq_l.en_gb AS quality_name_en_gb,
    iq_l.en_us AS quality_name_en_us,
    iq_l.es_es AS quality_name_es_es,
    iq_l.es_mx AS quality_name_es_mx,
    iq_l.fr_fr AS quality_name_fr_fr,
    iq_l.it_it AS quality_name_it_it,
    iq_l.ko_kr AS quality_name_ko_kr,
    iq_l.pt_br AS quality_name_pt_br,
    iq_l.pt_pt AS quality_name_pt_pt,
    iq_l.ru_ru AS quality_name_ru_ru,
    iq_l.zh_cn AS quality_name_zh_cn,
    iq_l.zh_tw AS quality_name_zh_tw,
    ic.id AS item_class_id,
    ic_l.de_de AS item_class_name_de_de,
    ic_l.en_gb AS item_class_name_en_gb,
    ic_l.en_us AS item_class_name_en_us,
    ic_l.es_es AS item_class_name_es_es,
    ic_l.es_mx AS item_class_name_es_mx,
    ic_l.fr_fr AS item_class_name_fr_fr,
    ic_l.it_it AS item_class_name_it_it,
    ic_l.ko_kr AS item_class_name_ko_kr,
    ic_l.pt_br AS item_class_name_pt_br,
    ic_l.pt_pt AS item_class_name_pt_pt,
    ic_l.ru_ru AS item_class_name_ru_ru,
    ic_l.zh_cn AS item_class_name_zh_cn,
    ic_l.zh_tw AS item_class_name_zh_tw,
    isc.internal_id AS item_subclass_internal_id,
    isc.subclass_id AS item_subclass_id,
    isc_l.de_de AS item_subclass_name_de_de,
    isc_l.en_gb AS item_subclass_name_en_gb,
    isc_l.en_us AS item_subclass_name_en_us,
    isc_l.es_es AS item_subclass_name_es_es,
    isc_l.es_mx AS item_subclass_name_es_mx,
    isc_l.fr_fr AS item_subclass_name_fr_fr,
    isc_l.it_it AS item_subclass_name_it_it,
    isc_l.ko_kr AS item_subclass_name_ko_kr,
    isc_l.pt_br AS item_subclass_name_pt_br,
    isc_l.pt_pt AS item_subclass_name_pt_pt,
    isc_l.ru_ru AS item_subclass_name_ru_ru,
    isc_l.zh_cn AS item_subclass_name_zh_cn,
    isc_l.zh_tw AS item_subclass_name_zh_tw,
    reci.id AS recipe_id,
    reci.media_url AS recipe_media_url,
    reci_l.de_de AS recipe_name_de_de,
    reci_l.en_gb AS recipe_name_en_gb,
    reci_l.en_us AS recipe_name_en_us,
    reci_l.es_es AS recipe_name_es_es,
    reci_l.es_mx AS recipe_name_es_mx,
    reci_l.fr_fr AS recipe_name_fr_fr,
    reci_l.it_it AS recipe_name_it_it,
    reci_l.ko_kr AS recipe_name_ko_kr,
    reci_l.pt_br AS recipe_name_pt_br,
    reci_l.pt_pt AS recipe_name_pt_pt,
    reci_l.ru_ru AS recipe_name_ru_ru,
    reci_l.zh_cn AS recipe_name_zh_cn,
    reci_l.zh_tw AS recipe_name_zh_tw
FROM item i
         LEFT JOIN locale i_l ON i.name_id = i_l.id
         LEFT JOIN item_quality iq ON iq.internal_id = i.quality_id
         LEFT JOIN locale iq_l ON iq_l.id = iq.name_id
         LEFT JOIN item_class ic ON ic.id = i.item_class_id
         LEFT JOIN locale ic_l ON ic.name_id = ic_l.id
         LEFT JOIN item_subclass isc ON
            isc.internal_id = i.item_subclass_id AND isc.class_id = i.item_class_id
         LEFT JOIN locale isc_l ON isc.display_name_id = isc_l.id
         LEFT JOIN recipe reci ON reci.crafted_item_id = i.id
         LEFT JOIN locale reci_l ON reci.name_id = reci_l.id;
