import fs from "node:fs";
import path from "node:path";
import { labelsForSplitStep } from "./labels.mjs";
import { PLANNING_DIR } from "./paths.mjs";

export function loadTopics() {
  const { topics } = JSON.parse(
    fs.readFileSync(path.join(PLANNING_DIR, "topics.json"), "utf8"),
  );
  return topics;
}

export function loadSplitTemplates() {
  const { templates } = JSON.parse(
    fs.readFileSync(path.join(PLANNING_DIR, "split-templates.json"), "utf8"),
  );
  return templates;
}

export function getTopic(topicId) {
  const topics = loadTopics();
  const topic = topics[topicId];
  if (!topic) {
    throw new Error(
      `Unknown topic: ${topicId}. Run: node scripts/github-issues/scaffold-issue.mjs --list`,
    );
  }
  return topic;
}

function section(name, items) {
  if (!items?.length) return "";
  return `### ${name}\n${items.map((i) => `- \`${i}\``).join("\n")}\n`;
}

function defaultOpenApiPaths(topic) {
  if (topic.openapi?.length) return topic.openapi;
  if (topic.backend?.some((p) => p.includes("openapi"))) {
    return [
      "openapi/",
      "bash scripts/openapi/generate-all.sh",
      "bash scripts/openapi/generate-all.sh",
    ];
  }
  return [];
}

export function buildIssueBody({
  summary,
  topic,
  parentNumber,
  blockedBy = [],
  blocks = [],
  parentTitle,
  appliedLabels,
}) {
  const deps = [];
  if (parentNumber) {
    deps.push(
      `**Parent:** #${parentNumber}${parentTitle ? ` — ${parentTitle}` : ""}`,
    );
  }
  if (blockedBy.length) {
    deps.push(`**Blocked by:** ${blockedBy.map((n) => `#${n}`).join(", ")}`);
  }
  if (blocks.length) {
    deps.push(`**Blocks:** ${blocks.map((n) => `#${n}`).join(", ")}`);
  }

  const dependencySection = deps.length
    ? `## Dependencies\n${deps.map((d) => `- ${d}`).join("\n")}\n\n`
    : "";

  return `## Problem
<!-- Who is affected and why this matters -->

## Solution
${summary}

${dependencySection}## Codebase touch points
${section("Backend", topic.backend)}${section("Frontend", topic.frontend)}${section("Database / migrations", topic.data)}${section("OpenAPI", defaultOpenApiPaths(topic))}${section("Infra / CI", topic.infra)}${section("Tests", topic.tests)}${section("Docs", topic.docs)}${topic.commands?.length ? section("Commands", topic.commands) : ""}${topic.relatedSkill ? `\n### Related skill\n- \`${topic.relatedSkill}\`\n` : ""}
## Acceptance criteria
- [ ] API behavior defined and documented in OpenAPI (if applicable)
- [ ] Flyway migration added when schema changes
- [ ] Integration tests for backend flows (\`backend/src/test/\`)
- [ ] Frontend UI wired to generated client (if applicable)
- [ ] i18n strings extracted when UI changes (\`bun run extract-i18n\` in \`frontend/\`)
- [ ] Manual verification steps listed below

## Verification
1. 
2. 

## Out of scope
- 

---
_Labels:_ ${(appliedLabels ?? topic.labels ?? ["enhancement"]).join(", ")}
_After filing: add a matcher to \`scripts/github-issues/audit/features.json\` for triage._
`;
}

export function listTopics() {
  return Object.entries(loadTopics())
    .sort(([a], [b]) => a.localeCompare(b))
    .map(([id, t]) => ({ id, summary: t.summary }));
}

export function listSplitTemplates() {
  return Object.entries(loadSplitTemplates()).map(([id, t]) => ({
    id,
    description: t.description,
    steps: t.steps.length,
  }));
}

export function buildSplitPlan(templateId, ctx) {
  const templates = loadSplitTemplates();
  const template = templates[templateId];
  if (!template) {
    throw new Error(
      `Unknown split template: ${templateId}. Use split-feature.mjs --list-templates`,
    );
  }

  const topic = getTopic(ctx.topicId);
  const feature = ctx.featureName || topic.summary;

  const interpolate = (s) =>
    s.replaceAll("{feature}", feature).replaceAll("{topic}", ctx.topicId);

  return template.steps.map((step) => {
    const stepTopicId = interpolate(step.topic ?? ctx.topicId);
    const stepTopic =
      stepTopicId === "openapi" ? getTopic("openapi") : getTopic(stepTopicId);
    const labelResolution = labelsForSplitStep({
      key: step.key,
      labels: step.labels,
      topic: stepTopic,
    });

    return {
      key: step.key,
      title: interpolate(step.titleTemplate),
      summary: interpolate(step.summaryTemplate ?? stepTopic.summary),
      topicId: stepTopicId,
      topic: stepTopic,
      labels: labelResolution.applied,
      labelUnknown: labelResolution.unknown,
      blockedByKeys: step.blockedBy ?? [],
    };
  });
}

export function renderParentTrackingBody(parentBody, created) {
  const section = [
    "",
    "## Sub-issues",
    "",
    ...created.map(
      (c) =>
        `- [ ] #${c.number} ${c.title}${c.blockedByNumbers?.length ? ` (blocked by ${c.blockedByNumbers.map((n) => `#${n}`).join(", ")})` : ""}`,
    ),
    "",
    "_Generated by `scripts/github-issues/split-feature.mjs`._",
  ].join("\n");

  if (parentBody.includes("## Sub-issues")) {
    return parentBody.replace(/\n## Sub-issues[\s\S]*$/, section);
  }
  return `${parentBody.trimEnd()}${section}`;
}
