CREATE TABLE `item_name_locale` (
                                    `id` int(11) NOT NULL,
                                    `en_GB` varchar(100) DEFAULT NULL,
                                    `en_US` varchar(100) DEFAULT NULL,
                                    `de_DE` varchar(100) DEFAULT NULL,
                                    `es_ES` varchar(100) DEFAULT NULL,
                                    `es_MX` varchar(100) DEFAULT NULL,
                                    `fr_FR` varchar(100) DEFAULT NULL,
                                    `it_IT` varchar(100) DEFAULT NULL,
                                    `pl_PL` varchar(100) DEFAULT NULL,
                                    `pt_PT` varchar(100) DEFAULT NULL,
                                    `pt_BR` varchar(100) DEFAULT NULL,
                                    `ru_RU` varchar(100) DEFAULT NULL,
                                    `ko_KR` varchar(100) DEFAULT NULL,
                                    `zh_TW` varchar(100) DEFAULT NULL,
                                    UNIQUE KEY `id_UNIQUE` (`id`),
                                    KEY `fk_items_locale_items_idx` (`id`),
                                    CONSTRAINT `fk_items_locale_items` FOREIGN KEY (`id`) REFERENCES `items` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 COLLATE=utf8mb3_general_ci

CREATE TABLE `itemClassic_name_locale` (
                                           `id` int(11) NOT NULL,
                                           `en_GB` varchar(100) DEFAULT NULL,
                                           `en_US` varchar(100) DEFAULT NULL,
                                           `de_DE` varchar(100) DEFAULT NULL,
                                           `es_ES` varchar(100) DEFAULT NULL,
                                           `es_MX` varchar(100) DEFAULT NULL,
                                           `fr_FR` varchar(100) DEFAULT NULL,
                                           `it_IT` varchar(100) DEFAULT NULL,
                                           `pl_PL` varchar(100) DEFAULT NULL,
                                           `pt_PT` varchar(100) DEFAULT NULL,
                                           `pt_BR` varchar(100) DEFAULT NULL,
                                           `ru_RU` varchar(100) DEFAULT NULL,
                                           `ko_KR` varchar(100) DEFAULT NULL,
                                           `zh_TW` varchar(100) DEFAULT NULL,
                                           UNIQUE KEY `id_UNIQUE` (`id`),
                                           KEY `fk_itemClassic_name_locale_items_idx` (`id`),
                                           CONSTRAINT `fk_items_locale_itemsClassic` FOREIGN KEY (`id`) REFERENCES `itemsClassic` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 COLLATE=utf8mb3_general_ci

CREATE TABLE `itemPriceHistoryPerDay` (
                                          `ahId` smallint(6) NOT NULL,
                                          `ahTypeId` int(4) NOT NULL DEFAULT 0,
                                          `itemId` mediumint(9) NOT NULL,
                                          `date` date NOT NULL,
                                          `petSpeciesId` smallint(6) NOT NULL,
                                          `bonusIds` varchar(256) NOT NULL,
                                          `minHour01` smallint(2) DEFAULT NULL,
                                          `min01` bigint(20) DEFAULT NULL,
                                          `avg01` bigint(20) DEFAULT NULL,
                                          `max01` bigint(20) DEFAULT NULL,
                                          `minQuantity01` bigint(20) DEFAULT NULL,
                                          `avgQuantity01` bigint(20) DEFAULT NULL,
                                          `maxQuantity01` bigint(20) DEFAULT NULL,
                                          `minHour02` smallint(2) DEFAULT NULL,
                                          `min02` bigint(20) DEFAULT NULL,
                                          `avg02` bigint(20) DEFAULT NULL,
                                          `max02` bigint(20) DEFAULT NULL,
                                          `minQuantity02` bigint(20) DEFAULT NULL,
                                          `avgQuantity02` bigint(20) DEFAULT NULL,
                                          `maxQuantity02` bigint(20) DEFAULT NULL,
                                          `minHour03` smallint(2) DEFAULT NULL,
                                          `min03` bigint(20) DEFAULT NULL,
                                          `avg03` bigint(20) DEFAULT NULL,
                                          `max03` bigint(20) DEFAULT NULL,
                                          `minQuantity03` bigint(20) DEFAULT NULL,
                                          `avgQuantity03` bigint(20) DEFAULT NULL,
                                          `maxQuantity03` bigint(20) DEFAULT NULL,
                                          `minHour04` smallint(2) DEFAULT NULL,
                                          `min04` bigint(20) DEFAULT NULL,
                                          `avg04` bigint(20) DEFAULT NULL,
                                          `max04` bigint(20) DEFAULT NULL,
                                          `minQuantity04` bigint(20) DEFAULT NULL,
                                          `avgQuantity04` bigint(20) DEFAULT NULL,
                                          `maxQuantity04` bigint(20) DEFAULT NULL,
                                          `minHour05` smallint(2) DEFAULT NULL,
                                          `min05` bigint(20) DEFAULT NULL,
                                          `avg05` bigint(20) DEFAULT NULL,
                                          `max05` bigint(20) DEFAULT NULL,
                                          `minQuantity05` bigint(20) DEFAULT NULL,
                                          `avgQuantity05` bigint(20) DEFAULT NULL,
                                          `maxQuantity05` bigint(20) DEFAULT NULL,
                                          `minHour06` smallint(2) DEFAULT NULL,
                                          `min06` bigint(20) DEFAULT NULL,
                                          `avg06` bigint(20) DEFAULT NULL,
                                          `max06` bigint(20) DEFAULT NULL,
                                          `minQuantity06` bigint(20) DEFAULT NULL,
                                          `avgQuantity06` bigint(20) DEFAULT NULL,
                                          `maxQuantity06` bigint(20) DEFAULT NULL,
                                          `minHour07` smallint(2) DEFAULT NULL,
                                          `min07` bigint(20) DEFAULT NULL,
                                          `avg07` bigint(20) DEFAULT NULL,
                                          `max07` bigint(20) DEFAULT NULL,
                                          `minQuantity07` bigint(20) DEFAULT NULL,
                                          `avgQuantity07` bigint(20) DEFAULT NULL,
                                          `maxQuantity07` bigint(20) DEFAULT NULL,
                                          `minHour08` smallint(2) DEFAULT NULL,
                                          `min08` bigint(20) DEFAULT NULL,
                                          `avg08` bigint(20) DEFAULT NULL,
                                          `max08` bigint(20) DEFAULT NULL,
                                          `minQuantity08` bigint(20) DEFAULT NULL,
                                          `avgQuantity08` bigint(20) DEFAULT NULL,
                                          `maxQuantity08` bigint(20) DEFAULT NULL,
                                          `minHour09` smallint(2) DEFAULT NULL,
                                          `min09` bigint(20) DEFAULT NULL,
                                          `avg09` bigint(20) DEFAULT NULL,
                                          `max09` bigint(20) DEFAULT NULL,
                                          `minQuantity09` bigint(20) DEFAULT NULL,
                                          `avgQuantity09` bigint(20) DEFAULT NULL,
                                          `maxQuantity09` bigint(20) DEFAULT NULL,
                                          `minHour10` smallint(2) DEFAULT NULL,
                                          `min10` bigint(20) DEFAULT NULL,
                                          `avg10` bigint(20) DEFAULT NULL,
                                          `max10` bigint(20) DEFAULT NULL,
                                          `minQuantity10` bigint(20) DEFAULT NULL,
                                          `avgQuantity10` bigint(20) DEFAULT NULL,
                                          `maxQuantity10` bigint(20) DEFAULT NULL,
                                          `minHour11` smallint(2) DEFAULT NULL,
                                          `min11` bigint(20) DEFAULT NULL,
                                          `avg11` bigint(20) DEFAULT NULL,
                                          `max11` bigint(20) DEFAULT NULL,
                                          `minQuantity11` bigint(20) DEFAULT NULL,
                                          `avgQuantity11` bigint(20) DEFAULT NULL,
                                          `maxQuantity11` bigint(20) DEFAULT NULL,
                                          `minHour12` smallint(2) DEFAULT NULL,
                                          `min12` bigint(20) DEFAULT NULL,
                                          `avg12` bigint(20) DEFAULT NULL,
                                          `max12` bigint(20) DEFAULT NULL,
                                          `minQuantity12` bigint(20) DEFAULT NULL,
                                          `avgQuantity12` bigint(20) DEFAULT NULL,
                                          `maxQuantity12` bigint(20) DEFAULT NULL,
                                          `minHour13` smallint(2) DEFAULT NULL,
                                          `min13` bigint(20) DEFAULT NULL,
                                          `avg13` bigint(20) DEFAULT NULL,
                                          `max13` bigint(20) DEFAULT NULL,
                                          `minQuantity13` bigint(20) DEFAULT NULL,
                                          `avgQuantity13` bigint(20) DEFAULT NULL,
                                          `maxQuantity13` bigint(20) DEFAULT NULL,
                                          `minHour14` smallint(2) DEFAULT NULL,
                                          `min14` bigint(20) DEFAULT NULL,
                                          `avg14` bigint(20) DEFAULT NULL,
                                          `max14` bigint(20) DEFAULT NULL,
                                          `minQuantity14` bigint(20) DEFAULT NULL,
                                          `avgQuantity14` bigint(20) DEFAULT NULL,
                                          `maxQuantity14` bigint(20) DEFAULT NULL,
                                          `minHour15` smallint(2) DEFAULT NULL,
                                          `min15` bigint(20) DEFAULT NULL,
                                          `avg15` bigint(20) DEFAULT NULL,
                                          `max15` bigint(20) DEFAULT NULL,
                                          `minQuantity15` bigint(20) DEFAULT NULL,
                                          `avgQuantity15` bigint(20) DEFAULT NULL,
                                          `maxQuantity15` bigint(20) DEFAULT NULL,
                                          `minHour16` smallint(2) DEFAULT NULL,
                                          `min16` bigint(20) DEFAULT NULL,
                                          `avg16` bigint(20) DEFAULT NULL,
                                          `max16` bigint(20) DEFAULT NULL,
                                          `minQuantity16` bigint(20) DEFAULT NULL,
                                          `avgQuantity16` bigint(20) DEFAULT NULL,
                                          `maxQuantity16` bigint(20) DEFAULT NULL,
                                          `minHour17` smallint(2) DEFAULT NULL,
                                          `min17` bigint(20) DEFAULT NULL,
                                          `avg17` bigint(20) DEFAULT NULL,
                                          `max17` bigint(20) DEFAULT NULL,
                                          `minQuantity17` bigint(20) DEFAULT NULL,
                                          `avgQuantity17` bigint(20) DEFAULT NULL,
                                          `maxQuantity17` bigint(20) DEFAULT NULL,
                                          `minHour18` smallint(2) DEFAULT NULL,
                                          `min18` bigint(20) DEFAULT NULL,
                                          `avg18` bigint(20) DEFAULT NULL,
                                          `max18` bigint(20) DEFAULT NULL,
                                          `minQuantity18` bigint(20) DEFAULT NULL,
                                          `avgQuantity18` bigint(20) DEFAULT NULL,
                                          `maxQuantity18` bigint(20) DEFAULT NULL,
                                          `minHour19` smallint(2) DEFAULT NULL,
                                          `min19` bigint(20) DEFAULT NULL,
                                          `avg19` bigint(20) DEFAULT NULL,
                                          `max19` bigint(20) DEFAULT NULL,
                                          `minQuantity19` bigint(20) DEFAULT NULL,
                                          `avgQuantity19` bigint(20) DEFAULT NULL,
                                          `maxQuantity19` bigint(20) DEFAULT NULL,
                                          `minHour20` smallint(2) DEFAULT NULL,
                                          `min20` bigint(20) DEFAULT NULL,
                                          `avg20` bigint(20) DEFAULT NULL,
                                          `max20` bigint(20) DEFAULT NULL,
                                          `minQuantity20` bigint(20) DEFAULT NULL,
                                          `avgQuantity20` bigint(20) DEFAULT NULL,
                                          `maxQuantity20` bigint(20) DEFAULT NULL,
                                          `minHour21` smallint(2) DEFAULT NULL,
                                          `min21` bigint(20) DEFAULT NULL,
                                          `avg21` bigint(20) DEFAULT NULL,
                                          `max21` bigint(20) DEFAULT NULL,
                                          `minQuantity21` bigint(20) DEFAULT NULL,
                                          `avgQuantity21` bigint(20) DEFAULT NULL,
                                          `maxQuantity21` bigint(20) DEFAULT NULL,
                                          `minHour22` smallint(2) DEFAULT NULL,
                                          `min22` bigint(20) DEFAULT NULL,
                                          `avg22` bigint(20) DEFAULT NULL,
                                          `max22` bigint(20) DEFAULT NULL,
                                          `minQuantity22` bigint(20) DEFAULT NULL,
                                          `avgQuantity22` bigint(20) DEFAULT NULL,
                                          `maxQuantity22` bigint(20) DEFAULT NULL,
                                          `minHour23` smallint(2) DEFAULT NULL,
                                          `min23` bigint(20) DEFAULT NULL,
                                          `avg23` bigint(20) DEFAULT NULL,
                                          `max23` bigint(20) DEFAULT NULL,
                                          `minQuantity23` bigint(20) DEFAULT NULL,
                                          `avgQuantity23` bigint(20) DEFAULT NULL,
                                          `maxQuantity23` bigint(20) DEFAULT NULL,
                                          `minHour24` smallint(2) DEFAULT NULL,
                                          `min24` bigint(20) DEFAULT NULL,
                                          `avg24` bigint(20) DEFAULT NULL,
                                          `max24` bigint(20) DEFAULT NULL,
                                          `minQuantity24` bigint(20) DEFAULT NULL,
                                          `avgQuantity24` bigint(20) DEFAULT NULL,
                                          `maxQuantity24` bigint(20) DEFAULT NULL,
                                          `minHour25` smallint(2) DEFAULT NULL,
                                          `min25` bigint(20) DEFAULT NULL,
                                          `avg25` bigint(20) DEFAULT NULL,
                                          `max25` bigint(20) DEFAULT NULL,
                                          `minQuantity25` bigint(20) DEFAULT NULL,
                                          `avgQuantity25` bigint(20) DEFAULT NULL,
                                          `maxQuantity25` bigint(20) DEFAULT NULL,
                                          `minHour26` smallint(2) DEFAULT NULL,
                                          `min26` bigint(20) DEFAULT NULL,
                                          `avg26` bigint(20) DEFAULT NULL,
                                          `max26` bigint(20) DEFAULT NULL,
                                          `minQuantity26` bigint(20) DEFAULT NULL,
                                          `avgQuantity26` bigint(20) DEFAULT NULL,
                                          `maxQuantity26` bigint(20) DEFAULT NULL,
                                          `minHour27` smallint(2) DEFAULT NULL,
                                          `min27` bigint(20) DEFAULT NULL,
                                          `avg27` bigint(20) DEFAULT NULL,
                                          `max27` bigint(20) DEFAULT NULL,
                                          `minQuantity27` bigint(20) DEFAULT NULL,
                                          `avgQuantity27` bigint(20) DEFAULT NULL,
                                          `maxQuantity27` bigint(20) DEFAULT NULL,
                                          `minHour28` smallint(2) DEFAULT NULL,
                                          `min28` bigint(20) DEFAULT NULL,
                                          `avg28` bigint(20) DEFAULT NULL,
                                          `max28` bigint(20) DEFAULT NULL,
                                          `minQuantity28` bigint(20) DEFAULT NULL,
                                          `avgQuantity28` bigint(20) DEFAULT NULL,
                                          `maxQuantity28` bigint(20) DEFAULT NULL,
                                          `minHour29` smallint(2) DEFAULT NULL,
                                          `min29` bigint(20) DEFAULT NULL,
                                          `avg29` bigint(20) DEFAULT NULL,
                                          `max29` bigint(20) DEFAULT NULL,
                                          `minQuantity29` bigint(20) DEFAULT NULL,
                                          `avgQuantity29` bigint(20) DEFAULT NULL,
                                          `maxQuantity29` bigint(20) DEFAULT NULL,
                                          `minHour30` smallint(2) DEFAULT NULL,
                                          `min30` bigint(20) DEFAULT NULL,
                                          `avg30` bigint(20) DEFAULT NULL,
                                          `max30` bigint(20) DEFAULT NULL,
                                          `minQuantity30` bigint(20) DEFAULT NULL,
                                          `avgQuantity30` bigint(20) DEFAULT NULL,
                                          `maxQuantity30` bigint(20) DEFAULT NULL,
                                          `minHour31` smallint(2) DEFAULT NULL,
                                          `min31` bigint(20) DEFAULT NULL,
                                          `avg31` bigint(20) DEFAULT NULL,
                                          `max31` bigint(20) DEFAULT NULL,
                                          `minQuantity31` bigint(20) DEFAULT NULL,
                                          `avgQuantity31` bigint(20) DEFAULT NULL,
                                          `maxQuantity31` bigint(20) DEFAULT NULL,
                                          PRIMARY KEY (`ahId`,`ahTypeId`,`itemId`,`date`,`petSpeciesId`,`bonusIds`),
                                          KEY `idx_date_and_house` (`ahId`,`date`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 COLLATE=utf8mb3_general_ci
 PARTITION BY HASH (month(`date`))
PARTITIONS 12

CREATE TABLE `itemPriceHistoryPerHour` (
                                           `ahId` smallint(6) NOT NULL,
                                           `ahTypeId` int(4) NOT NULL DEFAULT 0,
                                           `itemId` mediumint(9) NOT NULL,
                                           `date` date NOT NULL,
                                           `petSpeciesId` smallint(6) NOT NULL,
                                           `bonusIds` varchar(256) NOT NULL,
                                           `price00` bigint(20) DEFAULT NULL,
                                           `quantity00` bigint(20) DEFAULT NULL,
                                           `price01` bigint(20) DEFAULT NULL,
                                           `quantity01` bigint(20) DEFAULT NULL,
                                           `price02` bigint(20) DEFAULT NULL,
                                           `quantity02` bigint(20) DEFAULT NULL,
                                           `price03` bigint(20) DEFAULT NULL,
                                           `quantity03` bigint(20) DEFAULT NULL,
                                           `price04` bigint(20) DEFAULT NULL,
                                           `quantity04` bigint(20) DEFAULT NULL,
                                           `price05` bigint(20) DEFAULT NULL,
                                           `quantity05` bigint(20) DEFAULT NULL,
                                           `price06` bigint(20) DEFAULT NULL,
                                           `quantity06` bigint(20) DEFAULT NULL,
                                           `price07` bigint(20) DEFAULT NULL,
                                           `quantity07` bigint(20) DEFAULT NULL,
                                           `price08` bigint(20) DEFAULT NULL,
                                           `quantity08` bigint(20) DEFAULT NULL,
                                           `price09` bigint(20) DEFAULT NULL,
                                           `quantity09` bigint(20) DEFAULT NULL,
                                           `price10` bigint(20) DEFAULT NULL,
                                           `quantity10` bigint(20) DEFAULT NULL,
                                           `price11` bigint(20) DEFAULT NULL,
                                           `quantity11` bigint(20) DEFAULT NULL,
                                           `price12` bigint(20) DEFAULT NULL,
                                           `quantity12` bigint(20) DEFAULT NULL,
                                           `price13` bigint(20) DEFAULT NULL,
                                           `quantity13` bigint(20) DEFAULT NULL,
                                           `price14` bigint(20) DEFAULT NULL,
                                           `quantity14` bigint(20) DEFAULT NULL,
                                           `price15` bigint(20) DEFAULT NULL,
                                           `quantity15` bigint(20) DEFAULT NULL,
                                           `price16` bigint(20) DEFAULT NULL,
                                           `quantity16` bigint(20) DEFAULT NULL,
                                           `price17` bigint(20) DEFAULT NULL,
                                           `quantity17` bigint(20) DEFAULT NULL,
                                           `price18` bigint(20) DEFAULT NULL,
                                           `quantity18` bigint(20) DEFAULT NULL,
                                           `price19` bigint(20) DEFAULT NULL,
                                           `quantity19` bigint(20) DEFAULT NULL,
                                           `price20` bigint(20) DEFAULT NULL,
                                           `quantity20` bigint(20) DEFAULT NULL,
                                           `price21` bigint(20) DEFAULT NULL,
                                           `quantity21` bigint(20) DEFAULT NULL,
                                           `price22` bigint(20) DEFAULT NULL,
                                           `quantity22` bigint(20) DEFAULT NULL,
                                           `price23` bigint(20) DEFAULT NULL,
                                           `quantity23` bigint(20) DEFAULT NULL,
                                           PRIMARY KEY (`ahId`,`itemId`,`date`,`petSpeciesId`,`bonusIds`,`ahTypeId`),
                                           KEY `idx_date_and_house` (`ahId`,`date`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 COLLATE=utf8mb3_general_ci MAX_ROWS=82300000
 PARTITION BY HASH (to_days(`date`))
PARTITIONS 31

CREATE TABLE `items` (
                         `id` int(11) NOT NULL,
                         `name` varchar(100) NOT NULL,
                         `icon` varchar(100) NOT NULL DEFAULT 'inv_scroll_03',
                         `itemLevel` int(11) DEFAULT NULL,
                         `itemClass` int(11) DEFAULT 0,
                         `itemSubClass` int(11) DEFAULT 0,
                         `quality` int(11) NOT NULL DEFAULT 0,
                         `itemSpells` mediumtext DEFAULT NULL,
                         `itemSource` mediumtext DEFAULT NULL,
                         `buyPrice` int(11) DEFAULT 0,
                         `sellPrice` int(11) DEFAULT 0,
                         `itemBind` int(11) DEFAULT 0,
                         `minFactionId` int(11) DEFAULT 0,
                         `minReputation` int(11) DEFAULT 0,
                         `isDropped` tinyint(4) NOT NULL DEFAULT 0,
                         `timestamp` timestamp NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),
                         `expansionId` int(11) DEFAULT -1,
                         `stackable` int(11) DEFAULT 1,
                         `bonusStats` mediumtext DEFAULT NULL,
                         `bonusSummary` mediumtext DEFAULT NULL,
                         `isAuctionable` tinyint(4) DEFAULT NULL,
                         `nameDescriptionColor` varchar(10) DEFAULT NULL,
                         `upgradable` tinyint(4) DEFAULT NULL,
                         `availableContexts` mediumtext DEFAULT NULL,
                         `bonusLists` mediumtext DEFAULT NULL,
                         `inventoryType` int(11) DEFAULT NULL,
                         `equippable` tinyint(4) DEFAULT NULL,
                         `maxDurability` int(11) DEFAULT NULL,
                         `baseArmor` int(11) DEFAULT NULL,
                         `armor` int(11) DEFAULT NULL,
                         `displayInfoId` int(11) DEFAULT NULL,
                         `requiredLevel` int(11) DEFAULT NULL,
                         `description` varchar(256) DEFAULT NULL,
                         `requiredSkill` int(11) DEFAULT NULL,
                         `requiredSkillRank` int(11) DEFAULT NULL,
                         `context` varchar(56) DEFAULT NULL,
                         `weaponInfo` mediumtext DEFAULT NULL,
                         `maxCount` int(11) DEFAULT NULL,
                         `requiredAbility` mediumtext DEFAULT NULL,
                         `socketInfo` mediumtext DEFAULT NULL,
                         `hasSockets` tinyint(4) DEFAULT NULL,
                         `gemInfo` mediumtext DEFAULT NULL,
                         `containerSlots` int(11) DEFAULT NULL,
                         `azeriteClassPowers` mediumtext DEFAULT NULL,
                         `allowableClasses` mediumtext DEFAULT NULL,
                         `nameDescription` varchar(56) DEFAULT NULL,
                         `boundZone` mediumtext DEFAULT NULL,
                         `patch` varchar(45) DEFAULT NULL,
                         `modifiedCraftingId` int(11) DEFAULT NULL,
                         `modifiedCraftingCategoryId` int(11) DEFAULT NULL,
                         `tier` int(11) DEFAULT NULL,
                         PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 COLLATE=utf8mb3_general_ci

CREATE TABLE `itemsClassic` (
                                `id` int(11) NOT NULL,
                                `name` varchar(100) NOT NULL,
                                `icon` varchar(100) NOT NULL DEFAULT 'inv_scroll_03',
                                `itemLevel` int(11) DEFAULT NULL,
                                `itemClass` int(11) DEFAULT 0,
                                `itemSubClass` int(11) DEFAULT 0,
                                `quality` int(11) NOT NULL DEFAULT 0,
                                `itemSpells` mediumtext DEFAULT NULL,
                                `itemSource` mediumtext DEFAULT NULL,
                                `buyPrice` int(11) DEFAULT 0,
                                `sellPrice` int(11) DEFAULT 0,
                                `itemBind` int(11) DEFAULT 0,
                                `minFactionId` int(11) DEFAULT 0,
                                `minReputation` int(11) DEFAULT 0,
                                `isDropped` tinyint(4) NOT NULL DEFAULT 0,
                                `timestamp` timestamp NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),
                                `expansionId` int(11) DEFAULT -1,
                                `stackable` int(11) DEFAULT 1,
                                `bonusStats` mediumtext DEFAULT NULL,
                                `bonusSummary` mediumtext DEFAULT NULL,
                                `isAuctionable` tinyint(4) DEFAULT NULL,
                                `nameDescriptionColor` varchar(10) DEFAULT NULL,
                                `upgradable` tinyint(4) DEFAULT NULL,
                                `availableContexts` mediumtext DEFAULT NULL,
                                `bonusLists` mediumtext DEFAULT NULL,
                                `inventoryType` int(11) DEFAULT NULL,
                                `equippable` tinyint(4) DEFAULT NULL,
                                `maxDurability` int(11) DEFAULT NULL,
                                `baseArmor` int(11) DEFAULT NULL,
                                `armor` int(11) DEFAULT NULL,
                                `displayInfoId` int(11) DEFAULT NULL,
                                `requiredLevel` int(11) DEFAULT NULL,
                                `description` varchar(256) DEFAULT NULL,
                                `requiredSkill` int(11) DEFAULT NULL,
                                `requiredSkillRank` int(11) DEFAULT NULL,
                                `context` varchar(56) DEFAULT NULL,
                                `weaponInfo` mediumtext DEFAULT NULL,
                                `maxCount` int(11) DEFAULT NULL,
                                `requiredAbility` mediumtext DEFAULT NULL,
                                `socketInfo` mediumtext DEFAULT NULL,
                                `hasSockets` tinyint(4) DEFAULT NULL,
                                `gemInfo` mediumtext DEFAULT NULL,
                                `containerSlots` int(11) DEFAULT NULL,
                                `azeriteClassPowers` mediumtext DEFAULT NULL,
                                `allowableClasses` mediumtext DEFAULT NULL,
                                `nameDescription` varchar(56) DEFAULT NULL,
                                `boundZone` mediumtext DEFAULT NULL,
                                `patch` varchar(45) DEFAULT NULL,
                                `classicPhase` int(2) DEFAULT 0,
                                PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 COLLATE=utf8mb3_general_ci

CREATE TABLE `missing_items` (
                                 `id` int(11) NOT NULL,
                                 `classic` tinyint(4) NOT NULL DEFAULT 0,
                                 `timestamp` timestamp NULL DEFAULT current_timestamp(),
                                 PRIMARY KEY (`id`,`classic`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 COLLATE=utf8mb3_general_ci

CREATE TABLE `modifiedCraftingCompatibleCategory` (
                                                      `id` int(11) NOT NULL,
                                                      PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 COLLATE=utf8mb3_general_ci

CREATE TABLE `modifiedCraftingCompatibleCategoryName` (
                                                          `id` int(11) NOT NULL,
                                                          `en_GB` varchar(512) DEFAULT NULL,
                                                          `en_US` varchar(512) DEFAULT NULL,
                                                          `de_DE` varchar(512) DEFAULT NULL,
                                                          `es_ES` varchar(512) DEFAULT NULL,
                                                          `es_MX` varchar(512) DEFAULT NULL,
                                                          `fr_FR` varchar(512) DEFAULT NULL,
                                                          `it_IT` varchar(512) DEFAULT NULL,
                                                          `pl_PL` varchar(512) DEFAULT NULL,
                                                          `pt_PT` varchar(512) DEFAULT NULL,
                                                          `pt_BR` varchar(512) DEFAULT NULL,
                                                          `ru_RU` varchar(512) DEFAULT NULL,
                                                          `ko_KR` varchar(512) DEFAULT NULL,
                                                          `zh_TW` varchar(512) DEFAULT NULL,
                                                          `zh_CN` varchar(512) DEFAULT NULL,
                                                          PRIMARY KEY (`id`),
                                                          KEY `fk_modifiedCraftingSlotTypeDescription_slot_idx` (`id`),
                                                          CONSTRAINT `fk_compatibleCategoryName_compatibleCategory` FOREIGN KEY (`id`) REFERENCES `modifiedCraftingCompatibleCategory` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 COLLATE=utf8mb3_general_ci

CREATE TABLE `modifiedCraftingSlotType` (
                                            `id` int(11) NOT NULL,
                                            PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 COLLATE=utf8mb3_general_ci

CREATE TABLE `modifiedCraftingSlotTypeCompatibleCategory` (
                                                              `slotTypeId` int(11) NOT NULL,
                                                              `compatibleCategoryId` int(11) NOT NULL,
                                                              PRIMARY KEY (`slotTypeId`,`compatibleCategoryId`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 COLLATE=utf8mb3_general_ci

CREATE TABLE `modifiedCraftingSlotTypeDescription` (
                                                       `id` int(11) NOT NULL,
                                                       `en_GB` varchar(512) DEFAULT NULL,
                                                       `en_US` varchar(512) DEFAULT NULL,
                                                       `de_DE` varchar(512) DEFAULT NULL,
                                                       `es_ES` varchar(512) DEFAULT NULL,
                                                       `es_MX` varchar(512) DEFAULT NULL,
                                                       `fr_FR` varchar(512) DEFAULT NULL,
                                                       `it_IT` varchar(512) DEFAULT NULL,
                                                       `pl_PL` varchar(512) DEFAULT NULL,
                                                       `pt_PT` varchar(512) DEFAULT NULL,
                                                       `pt_BR` varchar(512) DEFAULT NULL,
                                                       `ru_RU` varchar(512) DEFAULT NULL,
                                                       `ko_KR` varchar(512) DEFAULT NULL,
                                                       `zh_TW` varchar(512) DEFAULT NULL,
                                                       `zh_CN` varchar(512) DEFAULT NULL,
                                                       PRIMARY KEY (`id`),
                                                       KEY `fk_modifiedCraftingSlotTypeDescription_slot_idx` (`id`),
                                                       CONSTRAINT `fk_modifiedCraftingSlotTypeDescription_modifiedCraftingSlotType` FOREIGN KEY (`id`) REFERENCES `modifiedCraftingSlotType` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 COLLATE=utf8mb3_general_ci

CREATE TABLE `modifiedCraftingSlotTypeName` (
                                                `id` int(11) NOT NULL,
                                                `en_GB` varchar(512) DEFAULT NULL,
                                                `en_US` varchar(512) DEFAULT NULL,
                                                `de_DE` varchar(512) DEFAULT NULL,
                                                `es_ES` varchar(512) DEFAULT NULL,
                                                `es_MX` varchar(512) DEFAULT NULL,
                                                `fr_FR` varchar(512) DEFAULT NULL,
                                                `it_IT` varchar(512) DEFAULT NULL,
                                                `pl_PL` varchar(512) DEFAULT NULL,
                                                `pt_PT` varchar(512) DEFAULT NULL,
                                                `pt_BR` varchar(512) DEFAULT NULL,
                                                `ru_RU` varchar(512) DEFAULT NULL,
                                                `ko_KR` varchar(512) DEFAULT NULL,
                                                `zh_TW` varchar(512) DEFAULT NULL,
                                                `zh_CN` varchar(512) DEFAULT NULL,
                                                PRIMARY KEY (`id`),
                                                KEY `fk_modifiedCraftingSlotTypeName_slot_idx` (`id`),
                                                CONSTRAINT `fk_modifiedCraftingSlotTypeName_modifiedCraftingSlotType` FOREIGN KEY (`id`) REFERENCES `modifiedCraftingSlotType` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 COLLATE=utf8mb3_general_ci

CREATE TABLE `npc` (
                       `id` int(11) NOT NULL,
                       `isAlliance` tinyint(4) NOT NULL DEFAULT 0,
                       `isHorde` tinyint(4) NOT NULL DEFAULT 0,
                       `minLevel` int(11) DEFAULT NULL,
                       `maxLevel` int(11) DEFAULT NULL,
                       `zoneId` int(11) DEFAULT NULL,
                       `expansionId` int(11) NOT NULL DEFAULT -1,
                       `patch` varchar(45) DEFAULT NULL,
                       `timestamp` timestamp NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),
                       PRIMARY KEY (`id`),
                       KEY `fk_npc_zone1_idx` (`zoneId`),
                       CONSTRAINT `fk_npc_zone1` FOREIGN KEY (`zoneId`) REFERENCES `zone` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 COLLATE=utf8mb3_general_ci

CREATE TABLE `npcCoordinates` (
                                  `id` int(11) NOT NULL,
                                  `x` double NOT NULL,
                                  `y` double NOT NULL,
                                  `timestamp` timestamp NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),
                                  PRIMARY KEY (`id`,`x`,`y`),
                                  KEY `fk_npcCoordinates_npc1_idx` (`id`),
                                  CONSTRAINT `fk_npcCoordinates_npc1` FOREIGN KEY (`id`) REFERENCES `npc` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 COLLATE=utf8mb3_general_ci

CREATE TABLE `npcDrops` (
                            `id` int(11) NOT NULL,
                            `npcId` int(11) NOT NULL,
                            `dropped` int(11) NOT NULL,
                            `outOf` int(11) NOT NULL,
                            `dropChance` float NOT NULL,
                            `timestamp` timestamp NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),
                            KEY `fk_items_has_npc_npc2_idx` (`npcId`),
                            CONSTRAINT `fk_items_has_npc_npc2` FOREIGN KEY (`npcId`) REFERENCES `npc` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 COLLATE=utf8mb3_general_ci

CREATE TABLE `npcName` (
                           `id` int(11) NOT NULL,
                           `en_GB` varchar(100) NOT NULL,
                           `en_US` varchar(100) NOT NULL,
                           `de_DE` varchar(100) NOT NULL,
                           `es_ES` varchar(100) NOT NULL,
                           `es_MX` varchar(100) NOT NULL,
                           `fr_FR` varchar(100) NOT NULL,
                           `it_IT` varchar(100) NOT NULL,
                           `pl_PL` varchar(100) NOT NULL,
                           `pt_PT` varchar(100) NOT NULL,
                           `pt_BR` varchar(100) NOT NULL,
                           `ru_RU` varchar(100) NOT NULL,
                           `ko_KR` varchar(100) NOT NULL,
                           `zh_TW` varchar(100) NOT NULL,
                           PRIMARY KEY (`id`),
                           CONSTRAINT `fk_npcName_npc1` FOREIGN KEY (`id`) REFERENCES `npc` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 COLLATE=utf8mb3_general_ci

CREATE TABLE `npcSells` (
                            `id` int(11) NOT NULL,
                            `npcId` int(11) NOT NULL,
                            `standing` int(11) DEFAULT NULL,
                            `stock` int(11) NOT NULL,
                            `price` int(11) NOT NULL,
                            `unitPrice` int(11) NOT NULL,
                            `stackSize` int(11) NOT NULL,
                            `currency` int(11) DEFAULT NULL,
                            `timestamp` timestamp NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),
                            PRIMARY KEY (`id`,`npcId`),
                            KEY `fk_items_has_npc_npc1_idx` (`npcId`),
                            CONSTRAINT `fk_items_has_npc_npc1` FOREIGN KEY (`npcId`) REFERENCES `npc` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 COLLATE=utf8mb3_general_ci

CREATE TABLE `npcSkins` (
                            `id` int(11) NOT NULL,
                            `npcId` int(11) NOT NULL,
                            `dropped` int(11) DEFAULT NULL,
                            `outOf` int(11) DEFAULT NULL,
                            `dropChance` float DEFAULT NULL,
                            `timestamp` timestamp NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),
                            PRIMARY KEY (`id`,`npcId`),
                            KEY `fk_skinns_has_npc` (`npcId`),
                            CONSTRAINT `fk_skinns_has_npc` FOREIGN KEY (`npcId`) REFERENCES `npc` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 COLLATE=utf8mb3_general_ci

CREATE TABLE `npcTag` (
                          `id` int(11) NOT NULL,
                          `en_GB` varchar(100) NOT NULL,
                          `en_US` varchar(100) NOT NULL,
                          `de_DE` varchar(100) NOT NULL,
                          `es_ES` varchar(100) NOT NULL,
                          `es_MX` varchar(100) NOT NULL,
                          `fr_FR` varchar(100) NOT NULL,
                          `it_IT` varchar(100) NOT NULL,
                          `pl_PL` varchar(100) NOT NULL,
                          `pt_PT` varchar(100) NOT NULL,
                          `pt_BR` varchar(100) NOT NULL,
                          `ru_RU` varchar(100) NOT NULL,
                          `ko_KR` varchar(100) NOT NULL,
                          `zh_TW` varchar(100) NOT NULL,
                          PRIMARY KEY (`id`),
                          CONSTRAINT `fk_npcTag_npc1` FOREIGN KEY (`id`) REFERENCES `npc` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 COLLATE=utf8mb3_general_ci

CREATE TABLE `pet_name_locale` (
                                   `speciesId` int(11) NOT NULL,
                                   `en_GB` varchar(100) DEFAULT NULL,
                                   `en_US` varchar(100) DEFAULT NULL,
                                   `de_DE` varchar(100) DEFAULT NULL,
                                   `es_ES` varchar(100) DEFAULT NULL,
                                   `es_MX` varchar(100) DEFAULT NULL,
                                   `fr_FR` varchar(100) DEFAULT NULL,
                                   `it_IT` varchar(100) DEFAULT NULL,
                                   `pl_PL` varchar(100) DEFAULT NULL,
                                   `pt_PT` varchar(100) DEFAULT NULL,
                                   `pt_BR` varchar(100) DEFAULT NULL,
                                   `ru_RU` varchar(100) DEFAULT NULL,
                                   `ko_KR` varchar(100) DEFAULT NULL,
                                   `zh_TW` varchar(100) DEFAULT NULL,
                                   UNIQUE KEY `speciesId_UNIQUE` (`speciesId`),
                                   KEY `fk_pet_name_locale_pets1_idx` (`speciesId`),
                                   CONSTRAINT `fk_pet_name_locale_pets1` FOREIGN KEY (`speciesId`) REFERENCES `pets` (`speciesId`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 COLLATE=utf8mb3_general_ci

CREATE TABLE `pets` (
                        `speciesId` int(11) NOT NULL,
                        `petTypeId` int(11) DEFAULT NULL,
                        `creatureId` int(11) DEFAULT NULL,
                        `name` varchar(45) DEFAULT NULL,
                        `icon` varchar(45) DEFAULT NULL,
                        `description` mediumtext DEFAULT NULL,
                        `source` varchar(255) DEFAULT NULL,
                        `timestamp` timestamp NULL DEFAULT current_timestamp(),
                        PRIMARY KEY (`speciesId`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 COLLATE=utf8mb3_general_ci

CREATE TABLE `professions` (
                               `id` int(11) NOT NULL,
                               `icon` varchar(128) DEFAULT NULL,
                               `type` varchar(45) DEFAULT NULL,
                               `timestamp` timestamp NULL DEFAULT current_timestamp(),
                               PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 COLLATE=utf8mb3_general_ci

CREATE TABLE `professionsDescription` (
                                          `id` int(11) NOT NULL,
                                          `en_GB` varchar(512) DEFAULT NULL,
                                          `en_US` varchar(512) DEFAULT NULL,
                                          `de_DE` varchar(512) DEFAULT NULL,
                                          `es_ES` varchar(512) DEFAULT NULL,
                                          `es_MX` varchar(512) DEFAULT NULL,
                                          `fr_FR` varchar(512) DEFAULT NULL,
                                          `it_IT` varchar(512) DEFAULT NULL,
                                          `pl_PL` varchar(512) DEFAULT NULL,
                                          `pt_PT` varchar(512) DEFAULT NULL,
                                          `pt_BR` varchar(512) DEFAULT NULL,
                                          `ru_RU` varchar(512) DEFAULT NULL,
                                          `ko_KR` varchar(512) DEFAULT NULL,
                                          `zh_TW` varchar(512) DEFAULT NULL,
                                          `zh_CN` varchar(512) DEFAULT NULL,
                                          PRIMARY KEY (`id`),
                                          KEY `fk_professionsName_professions1_idx` (`id`),
                                          CONSTRAINT `fk_professionsName_professions10` FOREIGN KEY (`id`) REFERENCES `professions` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 COLLATE=utf8mb3_general_ci

CREATE TABLE `professionSkillTiers` (
                                        `id` int(11) NOT NULL,
                                        `professionId` int(11) NOT NULL,
                                        `min` int(11) DEFAULT NULL,
                                        `max` int(11) DEFAULT NULL,
                                        PRIMARY KEY (`id`),
                                        KEY `fk_professionSkillTiers_professions1_idx` (`professionId`),
                                        CONSTRAINT `fk_professionSkillTiers_professions1` FOREIGN KEY (`professionId`) REFERENCES `professions` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 COLLATE=utf8mb3_general_ci

CREATE TABLE `professionSkillTiersName` (
                                            `id` int(11) NOT NULL,
                                            `en_GB` varchar(512) DEFAULT NULL,
                                            `en_US` varchar(512) DEFAULT NULL,
                                            `de_DE` varchar(512) DEFAULT NULL,
                                            `es_ES` varchar(512) DEFAULT NULL,
                                            `es_MX` varchar(512) DEFAULT NULL,
                                            `fr_FR` varchar(512) DEFAULT NULL,
                                            `it_IT` varchar(512) DEFAULT NULL,
                                            `pl_PL` varchar(512) DEFAULT NULL,
                                            `pt_PT` varchar(512) DEFAULT NULL,
                                            `pt_BR` varchar(512) DEFAULT NULL,
                                            `ru_RU` varchar(512) DEFAULT NULL,
                                            `ko_KR` varchar(512) DEFAULT NULL,
                                            `zh_TW` varchar(512) DEFAULT NULL,
                                            `zh_CN` varchar(512) DEFAULT NULL,
                                            PRIMARY KEY (`id`),
                                            KEY `fk_professionSkillTiersName_professionSkillTiers1_idx` (`id`),
                                            CONSTRAINT `fk_professionSkillTiersName_professionSkillTiers1` FOREIGN KEY (`id`) REFERENCES `professionSkillTiers` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 COLLATE=utf8mb3_general_ci

CREATE TABLE `professionsName` (
                                   `id` int(11) NOT NULL,
                                   `en_GB` varchar(512) DEFAULT NULL,
                                   `en_US` varchar(512) DEFAULT NULL,
                                   `de_DE` varchar(512) DEFAULT NULL,
                                   `es_ES` varchar(512) DEFAULT NULL,
                                   `es_MX` varchar(512) DEFAULT NULL,
                                   `fr_FR` varchar(512) DEFAULT NULL,
                                   `it_IT` varchar(512) DEFAULT NULL,
                                   `pl_PL` varchar(512) DEFAULT NULL,
                                   `pt_PT` varchar(512) DEFAULT NULL,
                                   `pt_BR` varchar(512) DEFAULT NULL,
                                   `ru_RU` varchar(512) DEFAULT NULL,
                                   `ko_KR` varchar(512) DEFAULT NULL,
                                   `zh_TW` varchar(512) DEFAULT NULL,
                                   `zh_CN` varchar(512) DEFAULT NULL,
                                   PRIMARY KEY (`id`),
                                   KEY `fk_professionsName_professions1_idx` (`id`),
                                   CONSTRAINT `fk_professionsName_professions1` FOREIGN KEY (`id`) REFERENCES `professions` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 COLLATE=utf8mb3_general_ci

CREATE TABLE `reagents` (
                            `recipeId` int(11) NOT NULL,
                            `itemId` int(11) NOT NULL,
                            `quantity` int(11) NOT NULL,
                            `isOptional` tinyint(1) NOT NULL DEFAULT 0,
                            PRIMARY KEY (`recipeId`,`itemId`),
                            KEY `fk_reagent_recipe1_idx` (`recipeId`),
                            CONSTRAINT `fk_reagent_recipe1` FOREIGN KEY (`recipeId`) REFERENCES `recipes` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 COLLATE=utf8mb3_general_ci

CREATE TABLE `reagentsClassic` (
                                   `recipeId` int(11) NOT NULL,
                                   `itemId` int(11) NOT NULL,
                                   `quantity` int(11) NOT NULL,
                                   `isOptional` tinyint(1) NOT NULL DEFAULT 0,
                                   PRIMARY KEY (`recipeId`,`itemId`),
                                   KEY `fk_reagent_recipe1_idx` (`recipeId`),
                                   CONSTRAINT `fk_reagentClassic_recipeClassic_classic` FOREIGN KEY (`recipeId`) REFERENCES `recipesClassic` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 COLLATE=utf8mb3_general_ci

CREATE TABLE `recipes` (
                           `id` int(11) NOT NULL,
                           `icon` varchar(128) DEFAULT NULL,
                           `rank` int(11) DEFAULT NULL,
                           `craftedItemId` int(11) DEFAULT NULL,
                           `hordeCraftedItemId` int(11) DEFAULT NULL,
                           `allianceCraftedItemId` int(11) DEFAULT NULL,
                           `minCount` int(11) NOT NULL DEFAULT 1,
                           `maxCount` int(11) DEFAULT NULL,
                           `procRate` float DEFAULT 1,
                           `timestamp` timestamp NOT NULL DEFAULT current_timestamp(),
                           `professionSkillTierId` int(11) DEFAULT NULL,
                           `type` varchar(128) DEFAULT NULL,
                           PRIMARY KEY (`id`),
                           KEY `fk_recipes_new_professionSkillTiers1_idx` (`professionSkillTierId`),
                           CONSTRAINT `fk_recipes_new_professionSkillTiers1` FOREIGN KEY (`professionSkillTierId`) REFERENCES `professionSkillTiers` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 COLLATE=utf8mb3_general_ci

CREATE TABLE `recipesBonusId` (
                                  `bonusId` int(11) NOT NULL,
                                  `recipeId` int(11) NOT NULL,
                                  PRIMARY KEY (`bonusId`,`recipeId`),
                                  KEY `fk_recipes_has_bonus_id` (`recipeId`),
                                  CONSTRAINT `fk_recipes_has_bonus_id` FOREIGN KEY (`recipeId`) REFERENCES `recipes` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 COLLATE=utf8mb3_general_ci

CREATE TABLE `recipesClassic` (
                                  `id` int(11) NOT NULL,
                                  `spellId` int(11) NOT NULL,
                                  `name` varchar(512) DEFAULT NULL,
                                  `icon` varchar(128) DEFAULT NULL,
                                  `rank` int(11) DEFAULT NULL,
                                  `craftedItemId` int(11) DEFAULT NULL,
                                  `hordeCraftedItemId` int(11) DEFAULT NULL,
                                  `allianceCraftedItemId` int(11) DEFAULT NULL,
                                  `minCount` int(11) NOT NULL DEFAULT 1,
                                  `maxCount` int(11) DEFAULT NULL,
                                  `procRate` float DEFAULT 1,
                                  `timestamp` timestamp NOT NULL DEFAULT current_timestamp(),
                                  `professionId` int(11) DEFAULT NULL,
                                  `professionSkillTierId` int(11) DEFAULT NULL,
                                  `type` varchar(128) DEFAULT NULL,
                                  PRIMARY KEY (`id`),
                                  KEY `fk_recipesClassic_new_professionSkillTiers1_idx` (`professionSkillTierId`),
                                  KEY `fk_recipesClassic_profession_idx` (`professionId`),
                                  CONSTRAINT `fk_recipesClassic_new_professionSkillTiers` FOREIGN KEY (`professionSkillTierId`) REFERENCES `professionSkillTiers` (`id`),
                                  CONSTRAINT `fk_recipesClassic_profession` FOREIGN KEY (`professionId`) REFERENCES `professions` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 COLLATE=utf8mb3_general_ci

CREATE TABLE `recipesClassicName` (
                                      `id` int(11) NOT NULL,
                                      `en_GB` varchar(512) DEFAULT NULL,
                                      `en_US` varchar(512) DEFAULT NULL,
                                      `de_DE` varchar(512) DEFAULT NULL,
                                      `es_ES` varchar(512) DEFAULT NULL,
                                      `es_MX` varchar(512) DEFAULT NULL,
                                      `fr_FR` varchar(512) DEFAULT NULL,
                                      `it_IT` varchar(512) DEFAULT NULL,
                                      `pl_PL` varchar(512) DEFAULT NULL,
                                      `pt_PT` varchar(512) DEFAULT NULL,
                                      `pt_BR` varchar(512) DEFAULT NULL,
                                      `ru_RU` varchar(512) DEFAULT NULL,
                                      `ko_KR` varchar(512) DEFAULT NULL,
                                      `zh_TW` varchar(512) DEFAULT NULL,
                                      `zh_CN` varchar(512) DEFAULT NULL,
                                      PRIMARY KEY (`id`),
                                      KEY `fk_recipesClassicName_recipesClassicName_idx` (`id`),
                                      CONSTRAINT `fk_recipesClassicName_recipe` FOREIGN KEY (`id`) REFERENCES `recipesClassic` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 COLLATE=utf8mb3_general_ci

CREATE TABLE `recipesDescription` (
                                      `id` int(11) NOT NULL,
                                      `en_GB` varchar(512) DEFAULT NULL,
                                      `en_US` varchar(512) DEFAULT NULL,
                                      `de_DE` varchar(512) DEFAULT NULL,
                                      `es_ES` varchar(512) DEFAULT NULL,
                                      `es_MX` varchar(512) DEFAULT NULL,
                                      `fr_FR` varchar(512) DEFAULT NULL,
                                      `it_IT` varchar(512) DEFAULT NULL,
                                      `pl_PL` varchar(512) DEFAULT NULL,
                                      `pt_PT` varchar(512) DEFAULT NULL,
                                      `pt_BR` varchar(512) DEFAULT NULL,
                                      `ru_RU` varchar(512) DEFAULT NULL,
                                      `ko_KR` varchar(512) DEFAULT NULL,
                                      `zh_TW` varchar(512) DEFAULT NULL,
                                      `zh_CN` varchar(512) DEFAULT NULL,
                                      PRIMARY KEY (`id`),
                                      KEY `fk_recipeName_recipe_idx` (`id`),
                                      CONSTRAINT `fk_recipeName_recipe0` FOREIGN KEY (`id`) REFERENCES `recipes` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 COLLATE=utf8mb3_general_ci

CREATE TABLE `recipesModifiedCraftingSlot` (
                                               `id` int(11) NOT NULL,
                                               `recipeId` int(11) NOT NULL,
                                               `sortOrder` int(11) NOT NULL,
                                               PRIMARY KEY (`id`,`recipeId`),
                                               KEY `idx_recipes_modified_crafting_slot_recipe_id_idx` (`recipeId`),
                                               CONSTRAINT `idx_recipes_modified_crafting_slot_recipe_id` FOREIGN KEY (`recipeId`) REFERENCES `recipes` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 COLLATE=utf8mb3_general_ci

CREATE TABLE `recipesName` (
                               `id` int(11) NOT NULL,
                               `en_GB` varchar(512) DEFAULT NULL,
                               `en_US` varchar(512) DEFAULT NULL,
                               `de_DE` varchar(512) DEFAULT NULL,
                               `es_ES` varchar(512) DEFAULT NULL,
                               `es_MX` varchar(512) DEFAULT NULL,
                               `fr_FR` varchar(512) DEFAULT NULL,
                               `it_IT` varchar(512) DEFAULT NULL,
                               `pl_PL` varchar(512) DEFAULT NULL,
                               `pt_PT` varchar(512) DEFAULT NULL,
                               `pt_BR` varchar(512) DEFAULT NULL,
                               `ru_RU` varchar(512) DEFAULT NULL,
                               `ko_KR` varchar(512) DEFAULT NULL,
                               `zh_TW` varchar(512) DEFAULT NULL,
                               `zh_CN` varchar(512) DEFAULT NULL,
                               PRIMARY KEY (`id`),
                               KEY `fk_recipeName_recipe_idx` (`id`),
                               CONSTRAINT `fk_recipeName_recipe` FOREIGN KEY (`id`) REFERENCES `recipes` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 COLLATE=utf8mb3_general_ci

CREATE TABLE `zone` (
                        `id` int(11) NOT NULL,
                        `territoryId` int(11) NOT NULL,
                        `typeId` int(11) NOT NULL,
                        `parentId` int(11) DEFAULT NULL,
                        `minLevel` varchar(45) NOT NULL,
                        `maxLevel` varchar(45) NOT NULL,
                        `timestamp` timestamp NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),
                        PRIMARY KEY (`id`),
                        KEY `fk_zone_territory1_idx` (`territoryId`),
                        KEY `fk_zone_zone1_idx` (`parentId`),
                        KEY `fk_zone_zoneType1_idx` (`typeId`),
                        CONSTRAINT `fk_zone_territory10` FOREIGN KEY (`territoryId`) REFERENCES `zoneTerritory` (`id`),
                        CONSTRAINT `fk_zone_zone10` FOREIGN KEY (`parentId`) REFERENCES `zone` (`id`),
                        CONSTRAINT `fk_zone_zoneType10` FOREIGN KEY (`typeId`) REFERENCES `zoneType` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 COLLATE=utf8mb3_general_ci

CREATE TABLE `zoneName` (
                            `id` int(11) NOT NULL,
                            `en_GB` varchar(100) NOT NULL,
                            `en_US` varchar(100) NOT NULL,
                            `de_DE` varchar(100) NOT NULL,
                            `es_ES` varchar(100) NOT NULL,
                            `es_MX` varchar(100) NOT NULL,
                            `fr_FR` varchar(100) NOT NULL,
                            `it_IT` varchar(100) NOT NULL,
                            `pl_PL` varchar(100) NOT NULL,
                            `pt_PT` varchar(100) NOT NULL,
                            `pt_BR` varchar(100) NOT NULL,
                            `ru_RU` varchar(100) NOT NULL,
                            `ko_KR` varchar(100) NOT NULL,
                            `zh_TW` varchar(100) NOT NULL,
                            PRIMARY KEY (`id`),
                            KEY `fk_zoneName_zone1_idx` (`id`),
                            CONSTRAINT `fk_zoneName_zone1` FOREIGN KEY (`id`) REFERENCES `zone` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 COLLATE=utf8mb3_general_ci

CREATE TABLE `zoneTerritory` (
                                 `id` int(11) NOT NULL,
                                 `en_GB` varchar(100) NOT NULL,
                                 `en_US` varchar(100) NOT NULL,
                                 `de_DE` varchar(100) NOT NULL,
                                 `es_ES` varchar(100) NOT NULL,
                                 `es_MX` varchar(100) NOT NULL,
                                 `fr_FR` varchar(100) NOT NULL,
                                 `it_IT` varchar(100) NOT NULL,
                                 `pl_PL` varchar(100) NOT NULL,
                                 `pt_PT` varchar(100) NOT NULL,
                                 `pt_BR` varchar(100) NOT NULL,
                                 `ru_RU` varchar(100) NOT NULL,
                                 `ko_KR` varchar(100) NOT NULL,
                                 `zh_TW` varchar(100) NOT NULL,
                                 PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 COLLATE=utf8mb3_general_ci

CREATE TABLE `zoneType` (
                            `id` int(11) NOT NULL,
                            `en_GB` varchar(100) NOT NULL,
                            `en_US` varchar(100) NOT NULL,
                            `de_DE` varchar(100) NOT NULL,
                            `es_ES` varchar(100) NOT NULL,
                            `es_MX` varchar(100) NOT NULL,
                            `fr_FR` varchar(100) NOT NULL,
                            `it_IT` varchar(100) NOT NULL,
                            `pl_PL` varchar(100) NOT NULL,
                            `pt_PT` varchar(100) NOT NULL,
                            `pt_BR` varchar(100) NOT NULL,
                            `ru_RU` varchar(100) NOT NULL,
                            `ko_KR` varchar(100) NOT NULL,
                            `zh_TW` varchar(100) NOT NULL,
                            PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 COLLATE=utf8mb3_general_ci

